### ISSUE TITLE
x86平台编译不通过，编译指令./build.sh host.gcc

### ISSUE THREAD

**Issue by Yoke365** [ShawnFeng0/uorb#1]
x86平台编译不通过，编译指令./build.sh host.gcc

**Comment by ShawnFeng0** [comment]
可以贴出错误信息么？

**Comment by Yoke365** [comment]
> 可以贴出错误信息么？不带参数能编译通过么？

应该是cmake版本的问题，我使用cmake3.18就没有问题了，之前是3.5.0
