### ISSUE TITLE
How can I check the result of the libuorb.a?

### ISSUE THREAD

**Issue by korkeep** [ShawnFeng0/uorb#4]
Hi, @ShawnFeng0 😀

I am working on my project of ensuring the security of the uORB.

As a result of the execution of *build.sh*, I checked that the *libuorb.a* file was created.

How can I verify that the *libuorb.a* library is working in the PX4 simulator?

If there is no way to check in the simulator, can you please tell me how to check the test result?

Thank you sincerely 🙏

**Comment by ShawnFeng0** [comment]
This is an independent inter-thread communication library and cannot be directly used in PX4. The uorb library here is ported from PX4 and has been improved.

In the examples directory are several examples of using C and C++. There are unit tests in the tests directory. Unit tests can try to ensure that the code base is safe and reliable. The unit test here is basically the same as the unit test of PX4::uorb, but gtest is used here.

When you execute build.sh, only the local gcc is used to generate the library, and there is no unit test.

The code base is built using cmake and contains examples and tests.

If you want to execute a separate unit test (tests/uorb_unit_test.cc), you can execute the following command in the uorb directory:

```shell
mkdir -p build
cd build
cmake -DUORB_BUILD_TESTS=ON ..
make uorb_test
./tests/uorb_test
```

If you want to use uorb's C++ example (examples/cpp_pub_sub/cpp_pub_sub.cc) execute the following command:

```shell
mkdir -p build
cd build
cmake -DUORB_BUILD_EXAMPLES=ON ..
make uorb_example_cpp_pub_sub
./examples/cpp_pub_sub/uorb_example_cpp_pub_sub
```

I thought everyone was familiar with cmake, so I didn't write it in detail. If you are familiar with cmake, you should be able to understand the entire build process from CMakeLists.txt.

**Comment by ShawnFeng0** [comment]
I have been using this uorb library as a multi-threaded communication framework in embedded linux projects.
If you use it in your project and encounter problems, please feel free to open an issue, I hope it is useful.
