### ISSUE TITLE
APP层向硬件底层写数据可以用UORB吗？

### ISSUE THREAD

**Issue by yihua-wang** [ShawnFeng0/uorb#5]
比如GUI任务控制LED设备亮灭

**Comment by ShawnFeng0** [comment]
可以的，你要理解这个是多线程之间共享数据的。指令也可以作为数据。
你可以看看PX4飞控中的应用https://github.com/PX4/PX4-Autopilot/tree/v1.12.3/msg，PX4在很多应用场景下都用了uorb.
你有成功跑起来么？在什么平台上？什么系统？需要支持么？

**Comment by yihua-wang** [comment]
我是想学习一下UORB源码，有在Linux平台上跑起来，只是还没完全搞清楚所有的使用场景

**Comment by ShawnFeng0** [comment]
uorb是典型的发布-订阅场景，以数据为核心，方便各个模块共享数据。

但是不适合请求-回复式的场景，这个我推荐用函数或者用别的机制。

我是希望这个库能被大家用起来的，如果需要详细交流可以加微信详细沟通，我微信号：shawnfeng0
